import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:1590,height:1000},deviceScaleFactor:2});
const p=await ctx.newPage();
await p.goto('file://'+new URL('../prototype/hcf-builder.html', import.meta.url).pathname,{waitUntil:'domcontentloaded'}); await p.waitForTimeout(700);
await p.locator('.rail').screenshot({path:'shots/v6-rail-empty.png'});
await p.locator('.tile').nth(0).click(); await p.waitForTimeout(400);
await p.locator('.sizes button').nth(1).click(); await p.waitForTimeout(120);
await p.locator('.qtys button').nth(2).click(); await p.waitForTimeout(120);
await p.locator('.qtys button').nth(3).click(); await p.waitForTimeout(120);
await p.locator('.lidrow input').check(); await p.waitForTimeout(120);
await p.locator('.config-foot .btn--primary').click(); await p.waitForTimeout(400);
await p.locator('.added__pills .tab',{hasText:'Mason Jars'}).click(); await p.waitForTimeout(500);
await p.locator('.sizes button').nth(0).click(); await p.waitForTimeout(120);
await p.locator('.qtys button').nth(1).click(); await p.waitForTimeout(120);
await p.locator('.config-foot .btn--primary').click(); await p.waitForTimeout(400);
await p.locator('.rail').screenshot({path:'shots/v6-rail-full.png'});
await p.evaluate(()=>window.scrollTo(0,0)); await p.waitForTimeout(300);
await p.screenshot({path:'shots/v6-page.png'});
await b.close(); console.log('shots done');
